# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: 'PowerShell Analyzer Action'
author: 'Ed-Fi Alliance'
description: 'Lint PowerShell scripts and modules using PSScriptAnalyzer'
branding:
  icon : alert-octagon
  color: blue
inputs:
  directory:  # id of input
    description: 'Path to analyze'
    required: true
    default: '.'
outputs:
  results:
    description: 'SARIF Report with the results'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.directory }}
