name: "🔧 Engineering Team Issue"
description: "Internal issue for Ed-Fi engineering team members only"
title: "[Engineering] "
labels: ["engineering"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Engineering Team Only
        
        This template is for Ed-Fi engineering team members only. 
        
        If you're not part of the engineering team, please use the [Ed-Fi Community Hub](https://community.ed-fi.org) for support.

  - type: textarea
    id: description
    attributes:
      label: "Issue Description"
      description: "Describe the issue or task"
      placeholder: "Clear description of the issue..."
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: "Acceptance Criteria"
      description: "What needs to be done to resolve this issue?"
      placeholder: "- [ ] Criteria 1\n- [ ] Criteria 2"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any additional information, screenshots, or context"
      placeholder: "Additional details..."
    validations:
      required: false