env:
  browser: false
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  # AirBnB complains about imports with extensions, but for ES modules they are
  # required, see https://nodejs.org/api/esm.html#esm_mandatory_file_extensions
  import/extensions: off
