# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: "Analyze Repository"

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.ps1'
      - '**/*.psm1'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.ps1'
      - '**/*.psm1'
  workflow_dispatch:

jobs:
  analyze:
    name: Linter
    uses: stephenfuqua/ed-fi-actions/.github/workflows/powershell-analyzer.yml@latest
