name: Run Unicode Control Character Scan

on:
  workflow_call:

jobs:
  check-for-bidirectional-characters:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo to Scan
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579  # v2.4.0

      - name: Bidirectional Trojan source detector
        uses: haveyoudebuggedit/trojansourcedetector@103b76ee743f7a666fd98dfaa15b4b7e314ca140 #Hash value for v1.1.0
