# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: "On Pull Request - Action Allowedlist"

on:
  pull_request:
    branches:
      - main
    paths:
      - "action-allowedlist/**/*.py"
      - "action-allowedlist/poetry.lock"
  workflow_dispatch:

permissions: read-all

jobs:
  test-action-allowedlist:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: action-allowedlist
    steps:
      - name: Checkout the Actions repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.12'
          cache: 'poetry'
          cache-dependency-path: |
            action-allowedlist/poetry.lock

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Lint code
        run: poetry run flake8 .

      - name: Run tests
        run: poetry run pytest

  event_file:
    name: Upload Event File
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: Event File
        path: ${{ github.event_path }}
