# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Analyze PowerShell

on:
  workflow_call:
  workflow_dispatch:

jobs:
  analyze-powershell:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout the Actions repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Actions
          path: Ed-Fi-Actions

      - name: Checkout the repo to review
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: testing-repo

      - name: Analyze
        uses: ./Ed-Fi-Actions/powershell-analyzer
        id: powershell-analyzer
        with:
          directory: ./testing-repo/

      - name: Upload SARIF as Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
            name: analysis-result
            path: ./results.sarif
            retention-days: 10

      - name: Upload SARIF to CodeQL
        uses: github/codeql-action/upload-sarif@2d92b76c45b91eb80fc44c74ce3fce0ee94e8f9d # v3.29.5
        with:
          sarif_file: ./results.sarif
