# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Analyze PowerShell

on:
  workflow_call:
  workflow_dispatch:

jobs:
  analyze-powershell:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - name: Checkout the Actions repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ github.repository_owner }}/Ed-Fi-Actions
          path: Ed-Fi-Actions

      - name: Checkout the repo to review
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: testing-repo

      - name: Analyze
        uses: ./Ed-Fi-Actions/powershell-analyzer
        id: powershell-analyzer
        with:
          directory: ./testing-repo/

      - name: Upload SARIF as Artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
            name: analysis-result
            path: ./results.sarif
            retention-days: 10

      - name: Upload SARIF to CodeQL
        uses: github/codeql-action/upload-sarif@cf7e9f23492505046de9a37830c3711dd0f25bb3 # codeql-bundle-v2.16.2
        with:
          sarif_file: ./results.sarif
