# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: Repo Security Scan
on:
  workflow_call:
  # The bidi scanner may need an external config for some repos, by default it does not ignore
  # .vsdx (Visio) files, this input allows for an external config (hosted in the repo calling
  # the scanner) with any extra file types to ignore. If no file is provided will run with defaults
    inputs:
      config-file-path:
        required: false
        type: string
        default: ''
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  action-allowedlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Actions repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846  # v3.0.0
        with:
          repository: Ed-Fi-Alliance-OSS/Ed-Fi-Actions
          path: Ed-Fi-Actions

      - name: Checkout the repo to Scan
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846  # v3.0.0
        with:
          path: testing-repo

      - name: Scan used actions
        uses: ./Ed-Fi-Actions/action-allowedlist
        id: scan-action

  bidi-scanner:
    # Temporarily disable the job while working on a replacement
    if: 1 == 2
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repo to Scan
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846  # v3.0.0

      - name: Bidirectional Trojan source detector
        uses: haveyoudebuggedit/trojansourcedetector@103b76ee743f7a666fd98dfaa15b4b7e314ca140 # v1.1.0
        with:
            config: ${{ inputs.config-file-path }}
